### ISSUE TITLE
http only ?

### ISSUE THREAD

**Issue by Nosirus** [11notes/docker-keeweb#1]
hi,
this docker looks very interesting, I'm looking for a simple method to use my keepass file.

would it be possible to have an option just for the local? I use a VPN I don't need to open the internet.

this docker [fraoustin/keeweb](https://github.com/fraoustin/keeweb) does it quite well, but it is no longer up to date at all and I can't get the webdav to work.

**Comment by 11notes** [comment]
I can’t really follow. Keeweb listens by default on HTTPS on port 8443 with a self-signed certificate. To access Keeweb in the best manner possible, put it behind a reverse proxy like Traefik. With a valid and proper TLS/SSL certificate.
