### ISSUE TITLE
Manifest unknown..

### ISSUE THREAD

**Issue by madcoda9000** [11notes/docker-keeweb#3]
I get the error "manifest unknown" when i try to pull your image..

![image](https://github.com/user-attachments/assets/798e937c-680d-4791-be44-700dbf7170fa)

**Comment by 11notes** [comment]
Keeweb has no latest tag: https://hub.docker.com/repository/docker/11notes/keeweb/tags, most of my repos have no latest tag 😉. I’m an avid believer that latest is a bad software practice.
